server:
  port: 8763

eureka:
  instance:
    hostname: eureka.server
    # 心跳间隔，5秒，需要调整客户端
    #leaseRenewalIntervalInSeconds: 5
    # 没有心跳的淘汰时间，10秒，需要调整客户端
    #lease-expiration-duration-in-seconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭自我保护模式
    enable-self-preservation: false
    # 心跳阈值计算周期，如果开启自我保护模式，减少这个可以尽可能减少发现时间
    # renewalThresholdUpdateIntervalMs: 120000
    # 禁用readOnlyCacheMap
    useReadOnlyResponseCache: false
    # 主动失效检测间隔(单位ms，默认1分钟)，需要 client 心跳时间对应，不能乱改
    # eviction-interval-timer-in-ms: 5000
